### ISSUE TITLE
test pull requests

### ISSUE THREAD

**Issue by gucio321** [AllenDang/giu#315]
@allenDang what about a github workflow, which will check if project is able to build?
or you can add `branch protection rule` to master with `Require test status` from travisCI to prevent unbuildable PR to be merged.

_Originally posted by @gucio321 in https://github.com/AllenDang/giu/issues/314#issuecomment-912970533_

**Comment by AllenDang** [comment]
@gucio321 Yeah, I'm reading the manual about how to enable test status now...

**Comment by gucio321** [comment]
ok, here is an example githu action to test giu app. if you want to use it - put it in .github/workflows/:


```yaml
name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  Building:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout out source code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: 'true'

      - if: startsWith(matrix.os,'ubuntu')
        name: Set up LibGL, Mesa & X11 libraries
        run: |
          sudo apt-get --allow-releaseinfo-change update
          sudo apt-get install -y libgtk-3-dev libasound2-dev libxxf86vm-dev
      - name: Set up Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16.x
        id: go

      - name: Cache Go modules
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: run go get
        run: go get -v -t -d ./...
      - name: build
        run: |
            go build examples/widgets/widgets.go

      - name: test
        run: |
          go test ./...
```
if getting glfw error - run go command with `xvfb-run --auto-servernum`
